name:                azure-exporter
version:             0.1.0
git:                 "https://gitlab.com/gavinkflam/azure-exporter.git"
license:             MIT
author:              "Gavin Lam"
maintainer:          "me@gavin.hk"
copyright:           "2018 Gavin Lam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README at <https://gitlab.com/gavinkflam/azure-exporter>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson >= 1.4 && < 1.5
  - bytestring
  - here >= 1.2 && < 1.3
  - http-client >= 0.5 && < 0.6
  - http-client-tls >= 0.3 && < 0.4
  - http-types >= 0.12 && < 0.13
  - lens >= 4.16 && < 4.17
  - scientific >= 0.3 && < 0.4
  - text
  - casing >= 0.1 && < 0.2

executables:
  azure-exporter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - azure-exporter
    - mtl >= 2.2 && < 2.3
    - scotty >= 0.11 && < 0.12
    - stm >= 2.5 && < 2.6
    - time >= 1.8 && < 1.9
    - lens >= 4.16 && < 4.17
    - text

tests:
  azure-exporter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - azure-exporter
