name:                azure-exporter
version:             0.1.0
git:                 "https://gitlab.com/gavinkflam/azure-exporter.git"
license:             MIT
author:              "Gavin Lam"
maintainer:          "me@gavin.hk"
copyright:           "2018 Gavin Lam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README at <https://gitlab.com/gavinkflam/azure-exporter>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  azure-exporter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - azure-exporter

tests:
  azure-exporter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - azure-exporter
