name:                azure-exporter
version:             0.4.3
git:                 "https://gitlab.com/gavinkflam/azure-exporter.git"
license:             MIT
author:              "Gavin Lam"
maintainer:          "me@gavin.hk"
copyright:           "2018 Gavin Lam"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README at <https://gitlab.com/gavinkflam/azure-exporter>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson >= 1.4 && < 1.5
  - bytestring
  - containers
  - casing >= 0.1 && < 0.2
  - free >= 5.0 && < 5.1
  - http-client >= 0.5 && < 0.6
  - http-client-tls >= 0.3 && < 0.4
  - http-types >= 0.12 && < 0.13
  - mtl >= 2.2 && < 2.3
  - scientific >= 0.3 && < 0.4
  - scotty >= 0.11 && < 0.12
  - stm >= 2.5 && < 2.6
  - text
  - time >= 1.8 && < 1.9
  - unordered-containers >= 0.2.9 && < 0.2.10
  - vector >= 0.12 && < 0.13

executables:
  azure-exporter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 1.4 && < 1.5
    - azure-exporter
    - bytestring
    - http-client >= 0.5 && < 0.6
    - http-client-tls >= 0.3 && < 0.4
    - mtl >= 2.2 && < 2.3
    - scotty >= 0.11 && < 0.12
    - stm >= 2.5 && < 2.6
    - time >= 1.8 && < 1.9
    - tuple >= 0.3 && < 0.4
    - text
    - wai-extra >= 3.0 && < 3.1

tests:
  azure-exporter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 1.4 && < 1.5
    - azure-exporter
    - bytestring
    - hspec >= 2.5 && < 2.6
    - http-client >= 0.5 && < 0.6
    - http-types >= 0.12 && < 0.13
    - QuickCheck >= 2.11 && < 2.12
    - scientific >= 0.3 && < 0.4
    - text
    - time >= 1.8 && < 1.9
    - unordered-containers >= 0.2.9 && < 0.2.10
    - vector >= 0.12 && < 0.13
